# Generated by Django 6.0.1 on 2026-01-21 06:14

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight_billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightrecord',
            name='is_multi_drop',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('CALCULATE', 'Calculated'), ('EXPORT', 'Exported'), ('MULTI_DROP_ADD', 'Multi-Drop Added'), ('MULTI_DROP_CALCULATE', 'Multi-Drop Calculated')], max_length=30)),
                ('user', models.CharField(blank=True, max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('calculation_details', models.JSONField(blank=True, null=True)),
                ('weight_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='weight_billing.weightrecord')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='audit_logs_timesta_e93820_idx'), models.Index(fields=['action'], name='audit_logs_action_31f574_idx'), models.Index(fields=['weight_record'], name='audit_logs_weight__5c3ad4_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeightDrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drop_number', models.IntegerField()),
                ('gross_weight', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tare_weight', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('net_weight', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
                ('weight_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drops', to='weight_billing.weightrecord')),
            ],
            options={
                'db_table': 'weight_drops',
                'ordering': ['drop_number'],
                'unique_together': {('weight_record', 'drop_number')},
            },
        ),
    ]
