# Generated by Django 6.0.1 on 2026-01-22 09:01

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight_billing', '0002_weightrecord_is_multi_drop_auditlog_weightdrop'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slip_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slip_number', models.CharField(max_length=100, unique=True)),
                ('printed_at', models.DateTimeField(auto_now_add=True)),
                ('slip_content', models.JSONField(blank=True, null=True)),
                ('printer_name', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Payment Slip',
                'verbose_name_plural': 'Payment Slips',
                'db_table': 'payment_slips',
                'ordering': ['-printed_at'],
            },
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('qr_string', models.TextField()),
                ('qr_image', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('scan_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'QR Code',
                'verbose_name_plural': 'QR Codes',
                'db_table': 'qr_codes',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('CALCULATE', 'Calculated'), ('EXPORT', 'Exported'), ('MULTI_DROP_ADD', 'Multi-Drop Added'), ('MULTI_DROP_CALCULATE', 'Multi-Drop Calculated'), ('PAYMENT_INITIATED', 'Payment Initiated'), ('QR_GENERATED', 'QR Code Generated'), ('SLIP_PRINTED', 'Slip Printed'), ('PAYMENT_SCANNED', 'QR Scanned'), ('PAYMENT_SUCCESS', 'Payment Success'), ('PAYMENT_FAILED', 'Payment Failed'), ('PAYMENT_UPDATED', 'Payment Updated')], max_length=30),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('payment_method', models.CharField(choices=[('UPI', 'UPI'), ('CASH', 'Cash'), ('CARD', 'Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('CHEQUE', 'Cheque')], default='UPI', max_length=20)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('upi_transaction_id', models.CharField(blank=True, max_length=200)),
                ('upi_transaction_ref', models.CharField(blank=True, max_length=200)),
                ('upi_qr_data', models.TextField(blank=True)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weight_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='weight_billing.weightrecord')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='auditlog',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='weight_billing.payment'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['payment'], name='audit_logs_payment_4a93fb_idx'),
        ),
        migrations.AddField(
            model_name='paymentslip',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slips', to='weight_billing.payment'),
        ),
        migrations.AddField(
            model_name='paymentslip',
            name='printed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printed_slips', to='weight_billing.operator'),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='weight_billing.payment'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_id'], name='payments_payment_2d1dd8_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_status'], name='payments_payment_bbdde9_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['weight_record'], name='payments_weight__c331e7_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['upi_transaction_id'], name='payments_upi_tra_50fa01_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentslip',
            index=models.Index(fields=['slip_id'], name='payment_sli_slip_id_a3eda7_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentslip',
            index=models.Index(fields=['slip_number'], name='payment_sli_slip_nu_fd08b3_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentslip',
            index=models.Index(fields=['payment'], name='payment_sli_payment_d75715_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['qr_id'], name='qr_codes_qr_id_00d989_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['payment'], name='qr_codes_payment_21a7d5_idx'),
        ),
    ]
