# Generated by Django 6.0.1 on 2026-01-23 05:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight_billing', '0003_paymentslip_qrcode_alter_auditlog_action_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=300)),
                ('company_address', models.TextField()),
                ('company_phone', models.CharField(blank=True, max_length=50)),
                ('company_email', models.EmailField(blank=True, max_length=254)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('gstin', models.CharField(blank=True, max_length=15)),
                ('pan', models.CharField(blank=True, max_length=10)),
                ('upi_id', models.CharField(blank=True, max_length=100)),
                ('upi_name', models.CharField(blank=True, max_length=200)),
                ('bank_name', models.CharField(blank=True, max_length=200)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('ifsc_code', models.CharField(blank=True, max_length=11)),
                ('slip_header_text', models.TextField(blank=True, help_text='Custom header text for slips')),
                ('slip_footer_text', models.TextField(blank=True, help_text='Custom footer text for slips')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Details',
                'verbose_name_plural': 'Company Details',
                'db_table': 'company_details',
            },
        ),
        migrations.CreateModel(
            name='WeightRecordPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='weight_records/%Y/%m/%d/')),
                ('photo_type', models.CharField(choices=[('VEHICLE_FRONT', 'Vehicle Front'), ('VEHICLE_BACK', 'Vehicle Back'), ('VEHICLE_SIDE', 'Vehicle Side'), ('MATERIAL', 'Material'), ('WEIGHBRIDGE', 'Weighbridge Display'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('display_order', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Weight Record Photo',
                'verbose_name_plural': 'Weight Record Photos',
                'db_table': 'weight_record_photos',
                'ordering': ['display_order', 'uploaded_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='paymentslip',
            options={'ordering': ['-created_at'], 'verbose_name': 'Payment Slip', 'verbose_name_plural': 'Payment Slips'},
        ),
        migrations.AddField(
            model_name='paymentslip',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='paymentslip',
            name='generated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='paymentslip',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_slips', to='weight_billing.operator'),
        ),
        migrations.AddField(
            model_name='paymentslip',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='slips/pdf/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='paymentslip',
            name='print_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paymentslip',
            name='slip_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('GENERATED', 'Generated'), ('PRINTED', 'Printed'), ('SENT', 'Sent'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentslip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('CALCULATE', 'Calculated'), ('EXPORT', 'Exported'), ('MULTI_DROP_ADD', 'Multi-Drop Added'), ('MULTI_DROP_CALCULATE', 'Multi-Drop Calculated'), ('PAYMENT_INITIATED', 'Payment Initiated'), ('QR_GENERATED', 'QR Code Generated'), ('SLIP_GENERATED', 'Slip Generated'), ('SLIP_PRINTED', 'Slip Printed'), ('PAYMENT_SCANNED', 'QR Scanned'), ('PAYMENT_SUCCESS', 'Payment Success'), ('PAYMENT_FAILED', 'Payment Failed'), ('PAYMENT_UPDATED', 'Payment Updated'), ('PHOTO_UPLOADED', 'Photo Uploaded'), ('PHOTO_DELETED', 'Photo Deleted')], max_length=30),
        ),
        migrations.AlterField(
            model_name='paymentslip',
            name='printed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='paymentslip',
            index=models.Index(fields=['slip_status'], name='payment_sli_slip_st_e152ec_idx'),
        ),
        migrations.AddField(
            model_name='weightrecordphoto',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_photos', to='weight_billing.operator'),
        ),
        migrations.AddField(
            model_name='weightrecordphoto',
            name='weight_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='weight_billing.weightrecord'),
        ),
        migrations.AddIndex(
            model_name='weightrecordphoto',
            index=models.Index(fields=['weight_record'], name='weight_reco_weight__7de79c_idx'),
        ),
        migrations.AddIndex(
            model_name='weightrecordphoto',
            index=models.Index(fields=['photo_type'], name='weight_reco_photo_t_89c5ac_idx'),
        ),
    ]
