# Generated by Django 6.0.1 on 2026-01-24 04:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight_billing', '0004_companydetails_weightrecordphoto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weightrecord',
            name='operator',
        ),
        migrations.AddField(
            model_name='weightrecord',
            name='first_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='weightrecord',
            name='first_weight_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weightrecord',
            name='operator_first_weight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_weight_records', to='weight_billing.operator'),
        ),
        migrations.AddField(
            model_name='weightrecord',
            name='operator_second_weight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_weight_records', to='weight_billing.operator'),
        ),
        migrations.AddField(
            model_name='weightrecord',
            name='second_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='weightrecord',
            name='second_weight_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weightrecord',
            name='slip_number',
            field=models.CharField(default='TEMP', editable=False, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weightrecord',
            name='status',
            field=models.CharField(choices=[('FIRST_WEIGHT_PENDING', 'First Weight Pending'), ('FIRST_WEIGHT_CAPTURED', 'First Weight Captured'), ('SECOND_WEIGHT_PENDING', 'Second Weight Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='FIRST_WEIGHT_PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='weightrecordphoto',
            name='weight_stage',
            field=models.CharField(choices=[('FIRST', 'First Weight'), ('SECOND', 'Second Weight'), ('BOTH', 'Both')], default='FIRST', max_length=10),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('CALCULATE', 'Calculated'), ('EXPORT', 'Exported'), ('MULTI_DROP_ADD', 'Multi-Drop Added'), ('MULTI_DROP_CALCULATE', 'Multi-Drop Calculated'), ('FIRST_WEIGHT_CAPTURED', 'First Weight Captured'), ('SECOND_WEIGHT_CAPTURED', 'Second Weight Captured'), ('WEIGHT_STABLE_DETECTED', 'Weight Stable Detected'), ('AUTO_CAPTURE', 'Auto Capture'), ('PAYMENT_INITIATED', 'Payment Initiated'), ('QR_GENERATED', 'QR Code Generated'), ('SLIP_GENERATED', 'Slip Generated'), ('SLIP_PRINTED', 'Slip Printed'), ('PAYMENT_SCANNED', 'QR Scanned'), ('PAYMENT_SUCCESS', 'Payment Success'), ('PAYMENT_FAILED', 'Payment Failed'), ('PAYMENT_UPDATED', 'Payment Updated'), ('PHOTO_UPLOADED', 'Photo Uploaded'), ('PHOTO_DELETED', 'Photo Deleted')], max_length=30),
        ),
        migrations.AlterField(
            model_name='weightrecord',
            name='gross_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='weightrecord',
            name='net_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='weightrecord',
            name='rate_per_unit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='weightrecord',
            name='tare_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='weightrecord',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='weightrecordphoto',
            name='photo_type',
            field=models.CharField(choices=[('VEHICLE_FRONT', 'Vehicle Front'), ('VEHICLE_BACK', 'Vehicle Back'), ('VEHICLE_SIDE', 'Vehicle Side'), ('MATERIAL', 'Material'), ('WEIGHBRIDGE', 'Weighbridge Display'), ('FIRST_WEIGHT', 'First Weight'), ('SECOND_WEIGHT', 'Second Weight'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddIndex(
            model_name='weightrecord',
            index=models.Index(fields=['status'], name='weight_reco_status_7883a9_idx'),
        ),
        migrations.AddIndex(
            model_name='weightrecord',
            index=models.Index(fields=['slip_number'], name='weight_reco_slip_nu_f9ae55_idx'),
        ),
        migrations.AddIndex(
            model_name='weightrecordphoto',
            index=models.Index(fields=['weight_stage'], name='weight_reco_weight__258b88_idx'),
        ),
    ]
