# Generated by Django 6.0.1 on 2026-01-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight_billing', '0005_remove_weightrecord_operator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightrecord',
            name='charges_calculated_time',
            field=models.DateTimeField(blank=True, help_text='When charges were calculated', null=True),
        ),
        migrations.AddField(
            model_name='weightrecord',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When weighment was completed', null=True),
        ),
        migrations.AddField(
            model_name='weightrecord',
            name='first_weight_auto_captured',
            field=models.BooleanField(default=False, help_text='Was first weight auto-captured by camera?'),
        ),
        migrations.AddField(
            model_name='weightrecord',
            name='first_weight_stable_detected_time',
            field=models.DateTimeField(blank=True, help_text='When first weight became stable', null=True),
        ),
        migrations.AddField(
            model_name='weightrecord',
            name='qr_generated_time',
            field=models.DateTimeField(blank=True, help_text='When QR code was generated', null=True),
        ),
        migrations.AddField(
            model_name='weightrecord',
            name='second_weight_auto_captured',
            field=models.BooleanField(default=False, help_text='Was second weight auto-captured by camera?'),
        ),
        migrations.AddField(
            model_name='weightrecord',
            name='second_weight_stable_detected_time',
            field=models.DateTimeField(blank=True, help_text='When second weight became stable', null=True),
        ),
        migrations.AddField(
            model_name='weightrecord',
            name='vehicle_left_time',
            field=models.DateTimeField(blank=True, help_text='When vehicle left after first weight', null=True),
        ),
        migrations.AddField(
            model_name='weightrecord',
            name='vehicle_returned_time',
            field=models.DateTimeField(blank=True, help_text='When vehicle returned for second weight', null=True),
        ),
        migrations.AddField(
            model_name='weightrecord',
            name='weights_calculated_time',
            field=models.DateTimeField(blank=True, help_text='When gross/tare/net were calculated', null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('CALCULATE', 'Calculated'), ('EXPORT', 'Exported'), ('MULTI_DROP_ADD', 'Multi-Drop Added'), ('MULTI_DROP_CALCULATE', 'Multi-Drop Calculated'), ('RECORD_SAVED', 'Record Saved in Database'), ('VEHICLE_LEFT', 'Vehicle Left'), ('FIRST_WEIGHT_STABLE_DETECTED', 'First Weight Stable Detected'), ('FIRST_WEIGHT_CAPTURED', 'First Weight Captured'), ('FIRST_WEIGHT_AUTO_CAPTURED', 'First Weight Auto-Captured'), ('VEHICLE_RETURNED', 'Vehicle Returned'), ('SECOND_WEIGHT_STABLE_DETECTED', 'Second Weight Stable Detected'), ('SECOND_WEIGHT_CAPTURED', 'Second Weight Captured'), ('SECOND_WEIGHT_AUTO_CAPTURED', 'Second Weight Auto-Captured'), ('WEIGHTS_CALCULATED', 'Weights Calculated'), ('CHARGES_CALCULATED', 'Charges Calculated'), ('PAYMENT_INITIATED', 'Payment Initiated'), ('QR_GENERATED', 'QR Code Generated'), ('SLIP_GENERATED', 'Slip Generated'), ('SLIP_PRINTED', 'Slip Printed'), ('PAYMENT_SCANNED', 'QR Scanned'), ('PAYMENT_SUCCESS', 'Payment Success'), ('PAYMENT_FAILED', 'Payment Failed'), ('PAYMENT_UPDATED', 'Payment Updated'), ('PHOTO_UPLOADED', 'Photo Uploaded'), ('PHOTO_DELETED', 'Photo Deleted'), ('WEIGHMENT_COMPLETE', 'Weighment Complete')], max_length=40),
        ),
        migrations.AlterField(
            model_name='weightrecord',
            name='status',
            field=models.CharField(choices=[('RECORD_SAVED', 'Record Saved in Database'), ('VEHICLE_LEFT', 'Vehicle Left'), ('FIRST_WEIGHT_PENDING', 'First Weight Pending'), ('FIRST_WEIGHT_STABLE', 'First Weight Stable Detected'), ('FIRST_WEIGHT_CAPTURED', 'First Weight Captured'), ('VEHICLE_RETURNED', 'Vehicle Returned'), ('SECOND_WEIGHT_PENDING', 'Second Weight Pending'), ('SECOND_WEIGHT_STABLE', 'Second Weight Stable Detected'), ('SECOND_WEIGHT_CAPTURED', 'Second Weight Captured'), ('WEIGHTS_CALCULATED', 'Weights Calculated'), ('CHARGES_CALCULATED', 'Charges Calculated'), ('QR_GENERATED', 'QR Code Generated'), ('COMPLETED', 'Weighment Complete'), ('CANCELLED', 'Cancelled')], default='RECORD_SAVED', max_length=30),
        ),
    ]
