# Generated by Django 6.0.1 on 2026-01-28 05:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight_billing', '0006_weightrecord_charges_calculated_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Camera identifier (e.g., Camera 1)', max_length=200)),
                ('camera_type', models.CharField(choices=[('USB', 'USB Camera'), ('IP', 'IP Camera'), ('RTSP', 'RTSP Stream')], default='USB', max_length=20)),
                ('position', models.CharField(choices=[('FRONT', 'Front'), ('BACK', 'Back'), ('LEFT', 'Left'), ('RIGHT', 'Right'), ('TOP', 'Top')], default='FRONT', max_length=20)),
                ('camera_index', models.IntegerField(default=0, help_text='USB camera index or IP camera ID')),
                ('rtsp_url', models.CharField(blank=True, help_text='RTSP URL for IP cameras (e.g., rtsp://192.168.1.100:554/stream)', max_length=500)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('auto_snapshot_enabled', models.BooleanField(default=True)),
                ('snapshot_on_first_weight', models.BooleanField(default=True)),
                ('snapshot_on_second_weight', models.BooleanField(default=True)),
                ('resolution_width', models.IntegerField(default=1920)),
                ('resolution_height', models.IntegerField(default=1080)),
                ('jpeg_quality', models.IntegerField(default=90, help_text='JPEG quality (1-100)')),
                ('show_on_dashboard', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_connected', models.BooleanField(default=False)),
                ('last_connected', models.DateTimeField(blank=True, null=True)),
                ('connection_status_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Camera Configuration',
                'verbose_name_plural': 'Camera Configurations',
                'db_table': 'camera_config',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LiveWeightReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_stable', models.BooleanField(default=False)),
                ('stability_started_at', models.DateTimeField(blank=True, null=True)),
                ('stability_duration', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='How long (seconds) weight has been stable', max_digits=5)),
                ('raw_data', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'live_weight_readings',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PrinterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('printer_type', models.CharField(choices=[('THERMAL', 'Thermal Printer'), ('LASER', 'Laser Printer'), ('INKJET', 'Inkjet Printer'), ('DOT_MATRIX', 'Dot Matrix Printer')], default='THERMAL', max_length=20)),
                ('printer_name', models.CharField(help_text='System printer name (from OS)', max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='For network printers', null=True)),
                ('port', models.IntegerField(default=9100, help_text='Network printer port')),
                ('paper_size', models.CharField(choices=[('80MM', '80mm (Thermal)'), ('58MM', '58mm (Thermal)'), ('A4', 'A4'), ('A5', 'A5'), ('LETTER', 'Letter')], default='80MM', max_length=20)),
                ('paper_width_mm', models.IntegerField(default=80)),
                ('auto_print_enabled', models.BooleanField(default=True, help_text='Automatically print slip when weighment is complete')),
                ('auto_print_copies', models.IntegerField(default=1, help_text='Number of copies to print automatically')),
                ('auto_print_on_completion', models.BooleanField(default=True, help_text='Print when status becomes COMPLETED')),
                ('is_ready', models.BooleanField(default=False)),
                ('slip_engine_ready', models.BooleanField(default=False, help_text='Whether the slip generation engine is initialized')),
                ('is_active', models.BooleanField(default=True)),
                ('is_connected', models.BooleanField(default=False)),
                ('last_printed', models.DateTimeField(blank=True, null=True)),
                ('connection_status_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Printer Configuration',
                'verbose_name_plural': 'Printer Configurations',
                'db_table': 'printer_config',
            },
        ),
        migrations.CreateModel(
            name='WeighbridgeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Main Weighbridge', max_length=200)),
                ('port', models.CharField(default='COM1', help_text='Serial port (e.g., COM1, /dev/ttyUSB0)', max_length=50)),
                ('baud_rate', models.IntegerField(default=9600)),
                ('data_bits', models.IntegerField(default=8)),
                ('stop_bits', models.IntegerField(default=1)),
                ('parity', models.CharField(choices=[('NONE', 'None'), ('EVEN', 'Even'), ('ODD', 'Odd')], default='NONE', max_length=10)),
                ('stability_threshold', models.DecimalField(decimal_places=2, default=Decimal('0.50'), help_text='Weight variance threshold (kg) for stability detection', max_digits=6)),
                ('stability_duration', models.IntegerField(default=3, help_text='Duration (seconds) weight must remain stable')),
                ('auto_capture_enabled', models.BooleanField(default=True)),
                ('auto_capture_delay', models.IntegerField(default=2, help_text='Delay (seconds) after stability before auto-capture')),
                ('is_connected', models.BooleanField(default=False)),
                ('last_connected', models.DateTimeField(blank=True, null=True)),
                ('connection_status_message', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Weighbridge Configuration',
                'verbose_name_plural': 'Weighbridge Configurations',
                'db_table': 'weighbridge_config',
            },
        ),
        migrations.AddField(
            model_name='paymentslip',
            name='auto_print_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paymentslip',
            name='auto_print_failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentslip',
            name='is_auto_printed',
            field=models.BooleanField(default=False, help_text='Was this slip auto-printed?'),
        ),
        migrations.AddField(
            model_name='weightrecord',
            name='current_live_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current weight being received from weighbridge', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='weightrecord',
            name='first_weight_stability_duration',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='How long first weight was stable (seconds)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='weightrecord',
            name='last_weight_update',
            field=models.DateTimeField(blank=True, help_text='Last time weight was updated from weighbridge', null=True),
        ),
        migrations.AddField(
            model_name='weightrecord',
            name='second_weight_stability_duration',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='How long second weight was stable (seconds)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='weightrecord',
            name='slip_auto_printed',
            field=models.BooleanField(default=False, help_text='Was slip auto-printed?'),
        ),
        migrations.AddField(
            model_name='weightrecord',
            name='slip_print_count',
            field=models.IntegerField(default=0, help_text='Number of times slip was printed'),
        ),
        migrations.AddField(
            model_name='weightrecord',
            name='slip_printed_time',
            field=models.DateTimeField(blank=True, help_text='When slip was printed', null=True),
        ),
        migrations.AddField(
            model_name='weightrecordphoto',
            name='captured_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight value when photo was captured', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='weightrecordphoto',
            name='is_auto_captured',
            field=models.BooleanField(default=False, help_text='Was this photo automatically captured on stable weight?'),
        ),
        migrations.AddField(
            model_name='weightrecordphoto',
            name='timestamp_added',
            field=models.BooleanField(default=False, help_text='Was timestamp added to image?'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('CALCULATE', 'Calculated'), ('EXPORT', 'Exported'), ('MULTI_DROP_ADD', 'Multi-Drop Added'), ('MULTI_DROP_CALCULATE', 'Multi-Drop Calculated'), ('RECORD_SAVED', 'Record Saved in Database'), ('VEHICLE_LEFT', 'Vehicle Left'), ('FIRST_WEIGHT_STABLE_DETECTED', 'First Weight Stable Detected'), ('FIRST_WEIGHT_CAPTURED', 'First Weight Captured'), ('FIRST_WEIGHT_AUTO_CAPTURED', 'First Weight Auto-Captured'), ('VEHICLE_RETURNED', 'Vehicle Returned'), ('SECOND_WEIGHT_STABLE_DETECTED', 'Second Weight Stable Detected'), ('SECOND_WEIGHT_CAPTURED', 'Second Weight Captured'), ('SECOND_WEIGHT_AUTO_CAPTURED', 'Second Weight Auto-Captured'), ('WEIGHTS_CALCULATED', 'Weights Calculated'), ('CHARGES_CALCULATED', 'Charges Calculated'), ('PAYMENT_INITIATED', 'Payment Initiated'), ('QR_GENERATED', 'QR Code Generated'), ('SLIP_GENERATED', 'Slip Generated'), ('SLIP_AUTO_PRINTED', 'Slip Auto-Printed'), ('SLIP_PRINTED', 'Slip Printed'), ('SLIP_PRINT_FAILED', 'Slip Print Failed'), ('PAYMENT_SCANNED', 'QR Scanned'), ('PAYMENT_SUCCESS', 'Payment Success'), ('PAYMENT_FAILED', 'Payment Failed'), ('PAYMENT_UPDATED', 'Payment Updated'), ('PHOTO_UPLOADED', 'Photo Uploaded'), ('PHOTO_AUTO_CAPTURED', 'Photo Auto-Captured'), ('PHOTO_DELETED', 'Photo Deleted'), ('TIMESTAMP_ADDED', 'Timestamp Added to Photo'), ('WEIGHBRIDGE_CONNECTED', 'Weighbridge Connected'), ('WEIGHBRIDGE_DISCONNECTED', 'Weighbridge Disconnected'), ('CAMERA_CONNECTED', 'Camera Connected'), ('CAMERA_DISCONNECTED', 'Camera Disconnected'), ('PRINTER_READY', 'Printer Ready'), ('PRINTER_NOT_READY', 'Printer Not Ready'), ('LIVE_WEIGHT_UPDATE', 'Live Weight Updated'), ('WEIGHMENT_COMPLETE', 'Weighment Complete')], max_length=40),
        ),
        migrations.AlterField(
            model_name='paymentslip',
            name='slip_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('GENERATED', 'Generated'), ('PRINTING', 'Printing'), ('PRINTED', 'Printed'), ('PRINT_FAILED', 'Print Failed'), ('SENT', 'Sent'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='weightrecord',
            name='first_weight_auto_captured',
            field=models.BooleanField(default=False, help_text='Was first weight auto-captured on stability?'),
        ),
        migrations.AlterField(
            model_name='weightrecord',
            name='second_weight_auto_captured',
            field=models.BooleanField(default=False, help_text='Was second weight auto-captured on stability?'),
        ),
        migrations.AlterField(
            model_name='weightrecord',
            name='status',
            field=models.CharField(choices=[('RECORD_SAVED', 'Record Saved in Database'), ('VEHICLE_LEFT', 'Vehicle Left'), ('FIRST_WEIGHT_PENDING', 'First Weight Pending'), ('FIRST_WEIGHT_STABLE', 'First Weight Stable Detected'), ('FIRST_WEIGHT_CAPTURED', 'First Weight Captured'), ('VEHICLE_RETURNED', 'Vehicle Returned'), ('SECOND_WEIGHT_PENDING', 'Second Weight Pending'), ('SECOND_WEIGHT_STABLE', 'Second Weight Stable Detected'), ('SECOND_WEIGHT_CAPTURED', 'Second Weight Captured'), ('WEIGHTS_CALCULATED', 'Weights Calculated'), ('CHARGES_CALCULATED', 'Charges Calculated'), ('QR_GENERATED', 'QR Code Generated'), ('SLIP_PRINTED', 'Slip Printed'), ('COMPLETED', 'Weighment Complete'), ('CANCELLED', 'Cancelled')], default='RECORD_SAVED', max_length=30),
        ),
        migrations.AlterField(
            model_name='weightrecordphoto',
            name='photo_type',
            field=models.CharField(choices=[('VEHICLE_FRONT', 'Vehicle Front'), ('VEHICLE_BACK', 'Vehicle Back'), ('VEHICLE_SIDE', 'Vehicle Side'), ('MATERIAL', 'Material'), ('WEIGHBRIDGE', 'Weighbridge Display'), ('FIRST_WEIGHT', 'First Weight'), ('SECOND_WEIGHT', 'Second Weight'), ('AUTO_SNAPSHOT', 'Auto Snapshot'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='weightrecordphoto',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captured_photos', to='weight_billing.cameraconfig'),
        ),
        migrations.AddIndex(
            model_name='weightrecordphoto',
            index=models.Index(fields=['is_auto_captured'], name='weight_reco_is_auto_119456_idx'),
        ),
        migrations.AddField(
            model_name='paymentslip',
            name='printer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printed_slips', to='weight_billing.printerconfig'),
        ),
        migrations.AddIndex(
            model_name='paymentslip',
            index=models.Index(fields=['is_auto_printed'], name='payment_sli_is_auto_78051f_idx'),
        ),
        migrations.AddField(
            model_name='liveweightreading',
            name='weighbridge_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_readings', to='weight_billing.weighbridgeconfig'),
        ),
        migrations.AddIndex(
            model_name='liveweightreading',
            index=models.Index(fields=['-timestamp'], name='live_weight_timesta_677c23_idx'),
        ),
        migrations.AddIndex(
            model_name='liveweightreading',
            index=models.Index(fields=['weighbridge_config', '-timestamp'], name='live_weight_weighbr_97b03f_idx'),
        ),
    ]
