# Generated by Django 6.0.1 on 2026-02-04 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weight_billing', '0007_cameraconfig_liveweightreading_printerconfig_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['driver_name']},
        ),
        migrations.AlterModelOptions(
            name='operator',
            options={'ordering': ['employee_name']},
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='driver_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='phone',
            new_name='driver_phone',
        ),
        migrations.RenameField(
            model_name='operator',
            old_name='name',
            new_name='employee_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
    ]
