# Generated by Django 6.0.1 on 2026-02-05 04:54

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight_billing', '0008_alter_customer_options_alter_operator_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIMonitoringConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='AI Monitoring System', max_length=200)),
                ('is_enabled', models.BooleanField(default=True)),
                ('detection_model', models.CharField(choices=[('YOLO_V8', 'YOLOv8 (Recommended)'), ('YOLO_V5', 'YOLOv5'), ('FASTER_RCNN', 'Faster R-CNN'), ('SSD', 'SSD MobileNet')], default='YOLO_V8', max_length=20)),
                ('model_confidence_threshold', models.DecimalField(decimal_places=2, default=Decimal('0.50'), help_text='Minimum confidence (0.0-1.0) for object detection', max_digits=3)),
                ('detection_interval_seconds', models.IntegerField(default=2, help_text='How often to run detection (seconds)')),
                ('authorized_object_classes', models.JSONField(default=list, help_text="List of authorized object classes (e.g., ['car', 'truck', 'bus', 'motorcycle'])")),
                ('alert_on_unauthorized_objects', models.BooleanField(default=True, help_text='Send alerts when non-vehicle objects are detected')),
                ('unauthorized_object_threshold', models.IntegerField(default=3, help_text='Number of consecutive detections before alerting')),
                ('alert_cooldown_seconds', models.IntegerField(default=60, help_text='Minimum time between alerts for same object type')),
                ('alert_on_person', models.BooleanField(default=True, help_text='Alert when person is detected in restricted area')),
                ('alert_on_animal', models.BooleanField(default=True, help_text='Alert when animal is detected')),
                ('alert_on_unknown_objects', models.BooleanField(default=True, help_text='Alert on objects that are not vehicles')),
                ('auto_snapshot_on_unauthorized', models.BooleanField(default=True, help_text='Automatically capture snapshot when unauthorized object detected')),
                ('send_email_alerts', models.BooleanField(default=False)),
                ('email_recipients', models.TextField(blank=True, help_text='Comma-separated email addresses')),
                ('send_sms_alerts', models.BooleanField(default=False)),
                ('sms_recipients', models.TextField(blank=True, help_text='Comma-separated phone numbers')),
                ('show_dashboard_alerts', models.BooleanField(default=True)),
                ('play_alert_sound', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_detection_run', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Monitoring Configuration',
                'verbose_name_plural': 'AI Monitoring Configurations',
                'db_table': 'ai_monitoring_config',
            },
        ),
        migrations.CreateModel(
            name='ObjectDetectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('CAR', 'Car'), ('TRUCK', 'Truck'), ('BUS', 'Bus'), ('MOTORCYCLE', 'Motorcycle'), ('BICYCLE', 'Bicycle'), ('PERSON', 'Person'), ('DOG', 'Dog'), ('CAT', 'Cat'), ('BIRD', 'Bird'), ('ANIMAL_OTHER', 'Other Animal'), ('UNKNOWN', 'Unknown Object')], max_length=20)),
                ('object_class', models.CharField(help_text='Raw class name from model', max_length=100)),
                ('confidence', models.DecimalField(decimal_places=4, help_text='Detection confidence (0.0-1.0)', max_digits=5)),
                ('bbox_x1', models.DecimalField(decimal_places=4, max_digits=6)),
                ('bbox_y1', models.DecimalField(decimal_places=4, max_digits=6)),
                ('bbox_x2', models.DecimalField(decimal_places=4, max_digits=6)),
                ('bbox_y2', models.DecimalField(decimal_places=4, max_digits=6)),
                ('is_authorized', models.BooleanField(default=False, help_text='Whether this object type is authorized in the area')),
                ('alert_triggered', models.BooleanField(default=False)),
                ('alert_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('snapshot_image', models.ImageField(blank=True, null=True, upload_to='detections/%Y/%m/%d/')),
                ('detection_count', models.IntegerField(default=1, help_text='Number of times this object was detected consecutively')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'object_detection_log',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='UnauthorizedPresenceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('alert_message', models.TextField()),
                ('object_description', models.CharField(max_length=200)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved'), ('FALSE_POSITIVE', 'False Positive')], default='ACTIVE', max_length=20)),
                ('alert_snapshot', models.ImageField(blank=True, null=True, upload_to='alerts/%Y/%m/%d/')),
                ('email_sent', models.BooleanField(default=False)),
                ('sms_sent', models.BooleanField(default=False)),
                ('dashboard_notified', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'unauthorized_presence_alerts',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.AddField(
            model_name='cameraconfig',
            name='ai_monitoring_enabled',
            field=models.BooleanField(default=False, help_text='Enable AI-based object detection and monitoring'),
        ),
        migrations.AddField(
            model_name='weightrecord',
            name='has_unauthorized_detections',
            field=models.BooleanField(default=False, help_text='Flag if unauthorized objects were detected during this weighment'),
        ),
        migrations.AddField(
            model_name='weightrecord',
            name='unauthorized_detection_count',
            field=models.IntegerField(default=0, help_text='Count of unauthorized detections during weighment'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('CALCULATE', 'Calculated'), ('EXPORT', 'Exported'), ('MULTI_DROP_ADD', 'Multi-Drop Added'), ('MULTI_DROP_CALCULATE', 'Multi-Drop Calculated'), ('RECORD_SAVED', 'Record Saved in Database'), ('VEHICLE_LEFT', 'Vehicle Left'), ('FIRST_WEIGHT_STABLE_DETECTED', 'First Weight Stable Detected'), ('FIRST_WEIGHT_CAPTURED', 'First Weight Captured'), ('FIRST_WEIGHT_AUTO_CAPTURED', 'First Weight Auto-Captured'), ('VEHICLE_RETURNED', 'Vehicle Returned'), ('SECOND_WEIGHT_STABLE_DETECTED', 'Second Weight Stable Detected'), ('SECOND_WEIGHT_CAPTURED', 'Second Weight Captured'), ('SECOND_WEIGHT_AUTO_CAPTURED', 'Second Weight Auto-Captured'), ('WEIGHTS_CALCULATED', 'Weights Calculated'), ('CHARGES_CALCULATED', 'Charges Calculated'), ('PAYMENT_INITIATED', 'Payment Initiated'), ('QR_GENERATED', 'QR Code Generated'), ('SLIP_GENERATED', 'Slip Generated'), ('SLIP_AUTO_PRINTED', 'Slip Auto-Printed'), ('SLIP_PRINTED', 'Slip Printed'), ('SLIP_PRINT_FAILED', 'Slip Print Failed'), ('PAYMENT_SCANNED', 'QR Scanned'), ('PAYMENT_SUCCESS', 'Payment Success'), ('PAYMENT_FAILED', 'Payment Failed'), ('PAYMENT_UPDATED', 'Payment Updated'), ('PHOTO_UPLOADED', 'Photo Uploaded'), ('PHOTO_AUTO_CAPTURED', 'Photo Auto-Captured'), ('PHOTO_DELETED', 'Photo Deleted'), ('TIMESTAMP_ADDED', 'Timestamp Added to Photo'), ('WEIGHBRIDGE_CONNECTED', 'Weighbridge Connected'), ('WEIGHBRIDGE_DISCONNECTED', 'Weighbridge Disconnected'), ('CAMERA_CONNECTED', 'Camera Connected'), ('CAMERA_DISCONNECTED', 'Camera Disconnected'), ('PRINTER_READY', 'Printer Ready'), ('PRINTER_NOT_READY', 'Printer Not Ready'), ('LIVE_WEIGHT_UPDATE', 'Live Weight Updated'), ('AI_MONITORING_ENABLED', 'AI Monitoring Enabled'), ('AI_MONITORING_DISABLED', 'AI Monitoring Disabled'), ('OBJECT_DETECTED', 'Object Detected'), ('UNAUTHORIZED_PRESENCE_DETECTED', 'Unauthorized Presence Detected'), ('PRESENCE_ALERT_TRIGGERED', 'Presence Alert Triggered'), ('PRESENCE_ALERT_ACKNOWLEDGED', 'Presence Alert Acknowledged'), ('PRESENCE_ALERT_RESOLVED', 'Presence Alert Resolved'), ('DETECTION_SNAPSHOT_CAPTURED', 'Detection Snapshot Captured'), ('WEIGHMENT_COMPLETE', 'Weighment Complete')], max_length=40),
        ),
        migrations.AlterField(
            model_name='weightrecordphoto',
            name='photo_type',
            field=models.CharField(choices=[('VEHICLE_FRONT', 'Vehicle Front'), ('VEHICLE_BACK', 'Vehicle Back'), ('VEHICLE_SIDE', 'Vehicle Side'), ('MATERIAL', 'Material'), ('WEIGHBRIDGE', 'Weighbridge Display'), ('FIRST_WEIGHT', 'First Weight'), ('SECOND_WEIGHT', 'Second Weight'), ('AUTO_SNAPSHOT', 'Auto Snapshot'), ('DETECTION_SNAPSHOT', 'Detection Snapshot'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddIndex(
            model_name='weightrecord',
            index=models.Index(fields=['has_unauthorized_detections'], name='weight_reco_has_una_abf35b_idx'),
        ),
        migrations.AddField(
            model_name='objectdetectionlog',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to='weight_billing.operator'),
        ),
        migrations.AddField(
            model_name='objectdetectionlog',
            name='camera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='weight_billing.cameraconfig'),
        ),
        migrations.AddField(
            model_name='objectdetectionlog',
            name='weight_record',
            field=models.ForeignKey(blank=True, help_text='Associated weight record if detection occurred during weighment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='weight_billing.weightrecord'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='detection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='weight_billing.objectdetectionlog'),
        ),
        migrations.AddField(
            model_name='weightrecordphoto',
            name='detection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='weight_billing.objectdetectionlog'),
        ),
        migrations.AddField(
            model_name='unauthorizedpresencealert',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_presence_alerts', to='weight_billing.operator'),
        ),
        migrations.AddField(
            model_name='unauthorizedpresencealert',
            name='camera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='weight_billing.cameraconfig'),
        ),
        migrations.AddField(
            model_name='unauthorizedpresencealert',
            name='detection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='weight_billing.objectdetectionlog'),
        ),
        migrations.AddField(
            model_name='unauthorizedpresencealert',
            name='weight_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presence_alerts', to='weight_billing.weightrecord'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='weight_billing.unauthorizedpresencealert'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['detection'], name='audit_logs_detecti_1bec96_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['alert'], name='audit_logs_alert_i_557a91_idx'),
        ),
        migrations.AddIndex(
            model_name='objectdetectionlog',
            index=models.Index(fields=['-detected_at'], name='object_dete_detecte_e0a24d_idx'),
        ),
        migrations.AddIndex(
            model_name='objectdetectionlog',
            index=models.Index(fields=['camera', '-detected_at'], name='object_dete_camera__0f769c_idx'),
        ),
        migrations.AddIndex(
            model_name='objectdetectionlog',
            index=models.Index(fields=['is_authorized'], name='object_dete_is_auth_374082_idx'),
        ),
        migrations.AddIndex(
            model_name='objectdetectionlog',
            index=models.Index(fields=['alert_triggered'], name='object_dete_alert_t_519e15_idx'),
        ),
        migrations.AddIndex(
            model_name='objectdetectionlog',
            index=models.Index(fields=['object_type'], name='object_dete_object__aea6a6_idx'),
        ),
        migrations.AddIndex(
            model_name='unauthorizedpresencealert',
            index=models.Index(fields=['alert_id'], name='unauthorize_alert_i_1b10cf_idx'),
        ),
        migrations.AddIndex(
            model_name='unauthorizedpresencealert',
            index=models.Index(fields=['-triggered_at'], name='unauthorize_trigger_17a38d_idx'),
        ),
        migrations.AddIndex(
            model_name='unauthorizedpresencealert',
            index=models.Index(fields=['status'], name='unauthorize_status_6b85ce_idx'),
        ),
        migrations.AddIndex(
            model_name='unauthorizedpresencealert',
            index=models.Index(fields=['severity'], name='unauthorize_severit_8ae4f4_idx'),
        ),
        migrations.AddIndex(
            model_name='unauthorizedpresencealert',
            index=models.Index(fields=['camera'], name='unauthorize_camera__2a97af_idx'),
        ),
    ]
