# Generated by Django 6.0.1 on 2026-02-07 04:50

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight_billing', '0009_aimonitoringconfig_objectdetectionlog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Backup System', max_length=200)),
                ('is_enabled', models.BooleanField(default=True)),
                ('backup_frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('CUSTOM', 'Custom Interval')], default='DAILY', max_length=20)),
                ('custom_interval_hours', models.IntegerField(default=24, help_text='For custom frequency, backup interval in hours')),
                ('backup_time', models.TimeField(default=datetime.time(2, 0), help_text='Preferred time for daily backups (24-hour format)')),
                ('backup_path', models.CharField(default='/backups/', help_text='Directory path for storing backups', max_length=500)),
                ('retention_days', models.IntegerField(default=90, help_text='Keep backups for this many days before auto-deletion')),
                ('keep_monthly_backups', models.BooleanField(default=True, help_text='Keep one backup per month indefinitely')),
                ('compress_backups', models.BooleanField(default=True, help_text='Compress backup files to save space')),
                ('include_media_files', models.BooleanField(default=True, help_text='Include uploaded media files in backup')),
                ('last_backup_date', models.DateTimeField(blank=True, null=True)),
                ('last_backup_status', models.CharField(blank=True, max_length=50)),
                ('last_backup_size_mb', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('send_backup_notifications', models.BooleanField(default=True)),
                ('notification_emails', models.TextField(blank=True, help_text='Comma-separated email addresses for backup notifications')),
                ('notify_on_success', models.BooleanField(default=False)),
                ('notify_on_failure', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Backup Configuration',
                'verbose_name_plural': 'Backup Configurations',
                'db_table': 'backup_config',
            },
        ),
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('backup_type', models.CharField(choices=[('AUTO', 'Automatic'), ('MANUAL', 'Manual'), ('SCHEDULED', 'Scheduled')], default='AUTO', max_length=20)),
                ('backup_status', models.CharField(choices=[('STARTED', 'Started'), ('IN_PROGRESS', 'In Progress'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial Success')], default='STARTED', max_length=20)),
                ('backup_file_path', models.CharField(blank=True, max_length=500)),
                ('backup_file_name', models.CharField(blank=True, max_length=200)),
                ('backup_size_mb', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('records_backed_up', models.IntegerField(default=0)),
                ('tables_backed_up', models.IntegerField(default=0)),
                ('media_files_backed_up', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('error_details', models.JSONField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'backup_logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DateLockConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Date Lock System', max_length=200)),
                ('is_enabled', models.BooleanField(default=True, help_text='Enable date-based record locking')),
                ('lock_days_after', models.IntegerField(default=7, help_text='Lock records after this many days (0 = lock immediately after date passes)')),
                ('allow_grace_period', models.BooleanField(default=True, help_text='Allow modifications during grace period')),
                ('grace_period_hours', models.IntegerField(default=24, help_text='Grace period in hours after date before lock takes effect')),
                ('super_admin_override', models.BooleanField(default=True, help_text='Allow super admins to edit locked records')),
                ('locked_dates', models.JSONField(default=list, help_text='List of specific dates that are permanently locked (YYYY-MM-DD format)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Date Lock Configuration',
                'verbose_name_plural': 'Date Lock Configurations',
                'db_table': 'date_lock_config',
            },
        ),
        migrations.CreateModel(
            name='SecurityAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200)),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('VIEW', 'Viewed'), ('SOFT_DELETE', 'Soft Deleted'), ('RESTORE', 'Restored'), ('DATE_LOCKED', 'Date Locked'), ('DATE_LOCK_OVERRIDE', 'Date Lock Overridden'), ('DATE_LOCK_ATTEMPT_BLOCKED', 'Date Lock Attempt Blocked'), ('BACKUP_STARTED', 'Backup Started'), ('BACKUP_COMPLETED', 'Backup Completed'), ('BACKUP_FAILED', 'Backup Failed'), ('BACKUP_VERIFIED', 'Backup Verified'), ('TARE_HISTORY_RECORDED', 'Tare Weight History Recorded'), ('TARE_VARIANCE_DETECTED', 'Tare Weight Variance Detected'), ('TARE_OUTLIER_DETECTED', 'Tare Weight Outlier Detected'), ('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('LOGIN_FAILED', 'Login Failed'), ('PERMISSION_DENIED', 'Permission Denied'), ('UNAUTHORIZED_ACCESS', 'Unauthorized Access Attempt'), ('CONFIG_CHANGED', 'Configuration Changed'), ('SECURITY_SETTING_CHANGED', 'Security Setting Changed')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('affected_model', models.CharField(blank=True, help_text='Model that was affected', max_length=100)),
                ('affected_object_id', models.IntegerField(blank=True, null=True)),
                ('is_suspicious', models.BooleanField(default=False, help_text='Flag for suspicious activity')),
                ('requires_review', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Security Audit Log',
                'verbose_name_plural': 'Security Audit Logs',
                'db_table': 'security_audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TareWeightHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tare_weight', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('recorded_date', models.DateField()),
                ('recorded_time', models.DateTimeField()),
                ('previous_tare_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weight_variance', models.DecimalField(blank=True, decimal_places=2, help_text='Difference from previous tare weight', max_digits=10, null=True)),
                ('variance_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage variance from previous tare', max_digits=5, null=True)),
                ('is_significant_variance', models.BooleanField(default=False, help_text='Flag if variance exceeds threshold (>5%)')),
                ('variance_notes', models.TextField(blank=True)),
                ('is_outlier', models.BooleanField(default=False, help_text='Statistical outlier based on historical data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tare Weight History',
                'verbose_name_plural': 'Tare Weight Histories',
                'db_table': 'tare_weight_history',
                'ordering': ['-recorded_date', '-recorded_time'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operator',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operator',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_known_tare',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Most recent tare weight recorded', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_tare_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weightrecord',
            name='date_locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weightrecord',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weightrecord',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weightrecord',
            name='is_date_locked',
            field=models.BooleanField(default=False, help_text="Whether this record's date is locked from editing"),
        ),
        migrations.AddField(
            model_name='weightrecord',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weightrecord',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_weight_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weightrecord',
            name='modification_count',
            field=models.IntegerField(default=0, help_text='Number of times record has been modified'),
        ),
        migrations.AddIndex(
            model_name='weightrecord',
            index=models.Index(fields=['is_date_locked'], name='weight_reco_is_date_9c019e_idx'),
        ),
        migrations.AddField(
            model_name='backuplog',
            name='backup_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_logs', to='weight_billing.backupconfig'),
        ),
        migrations.AddField(
            model_name='backuplog',
            name='initiated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_backups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securityauditlog',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_security_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securityauditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securityauditlog',
            name='weight_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_audit_logs', to='weight_billing.weightrecord'),
        ),
        migrations.AddField(
            model_name='tareweighthistory',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_tare_weights', to='weight_billing.operator'),
        ),
        migrations.AddField(
            model_name='tareweighthistory',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tare_history', to='weight_billing.vehicle'),
        ),
        migrations.AddField(
            model_name='tareweighthistory',
            name='weight_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tare_history_entries', to='weight_billing.weightrecord'),
        ),
        migrations.AddIndex(
            model_name='backuplog',
            index=models.Index(fields=['backup_id'], name='backup_logs_backup__49c239_idx'),
        ),
        migrations.AddIndex(
            model_name='backuplog',
            index=models.Index(fields=['-started_at'], name='backup_logs_started_43562f_idx'),
        ),
        migrations.AddIndex(
            model_name='backuplog',
            index=models.Index(fields=['backup_status'], name='backup_logs_backup__abbc2c_idx'),
        ),
        migrations.AddIndex(
            model_name='securityauditlog',
            index=models.Index(fields=['-timestamp'], name='security_au_timesta_fb0cbc_idx'),
        ),
        migrations.AddIndex(
            model_name='securityauditlog',
            index=models.Index(fields=['action'], name='security_au_action_5aa56f_idx'),
        ),
        migrations.AddIndex(
            model_name='securityauditlog',
            index=models.Index(fields=['weight_record'], name='security_au_weight__bb7e23_idx'),
        ),
        migrations.AddIndex(
            model_name='securityauditlog',
            index=models.Index(fields=['user'], name='security_au_user_id_57c443_idx'),
        ),
        migrations.AddIndex(
            model_name='securityauditlog',
            index=models.Index(fields=['is_suspicious'], name='security_au_is_susp_240854_idx'),
        ),
        migrations.AddIndex(
            model_name='securityauditlog',
            index=models.Index(fields=['requires_review'], name='security_au_require_de787e_idx'),
        ),
        migrations.AddIndex(
            model_name='securityauditlog',
            index=models.Index(fields=['affected_model', 'affected_object_id'], name='security_au_affecte_8e272b_idx'),
        ),
        migrations.AddIndex(
            model_name='tareweighthistory',
            index=models.Index(fields=['vehicle', '-recorded_date'], name='tare_weight_vehicle_dda086_idx'),
        ),
        migrations.AddIndex(
            model_name='tareweighthistory',
            index=models.Index(fields=['history_id'], name='tare_weight_history_0476e8_idx'),
        ),
        migrations.AddIndex(
            model_name='tareweighthistory',
            index=models.Index(fields=['-recorded_date'], name='tare_weight_recorde_1d5240_idx'),
        ),
        migrations.AddIndex(
            model_name='tareweighthistory',
            index=models.Index(fields=['is_significant_variance'], name='tare_weight_is_sign_85024c_idx'),
        ),
    ]
